//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
            this.PostImages = new HashSet<PostImage>();
            this.PostTags = new HashSet<PostTag>();
        }
    
        public int PostID { get; set; }
        public string Title { get; set; }
        public string ShortContent { get; set; }
        public string PostContent { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string SeoLink { get; set; }
        public Nullable<bool> Slider { get; set; }
        public Nullable<bool> Area1 { get; set; }
        public Nullable<bool> Area2 { get; set; }
        public Nullable<bool> Area3 { get; set; }
        public Nullable<bool> Notification { get; set; }
        public string LanguageName { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual T_User T_User { get; set; }
        public virtual ICollection<PostImage> PostImages { get; set; }
        public virtual ICollection<PostTag> PostTags { get; set; }
    }
}
